---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-workload-rollout-api.fullname" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-workload-rollout-api.fullname" . }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-workload-rollout-api.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-workload-rollout-api.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "k8s-workload-rollout-api.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
