---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-workload-rollout-api.fullname" . }}
  labels:
    {{- include "k8s-workload-rollout-api.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.csv: |
    {{- include "k8s-workload-rollout-api.credentials" . | b64enc | nindent 4 }}
  repositories.csv: |
    {{- include "k8s-workload-rollout-api.repositories" . | b64enc | nindent 4 }}