apiVersion: v1
kind: Service
metadata:
  name: {{ include "short_name" . }}
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "short_name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP
