apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "short_name" . }}
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "short_name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ include "chart_labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "short_name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ include "chart_labels" . | indent 8 }}
      annotations:
    spec:
      {{- with .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ . }}
      {{- end }}
      containers:
        - name: postfix
          image: {{ .Values.image | quote }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.imagePullPolicy }}
          resources:
            limits:
            {{- with .Values.limits.memory }}
              memory: "{{ . }}"
            {{- end }}
            {{- with .Values.limits.cpu }}
              cpu: "{{ . }}"
            {{- end }}
            requests:
            {{- with .Values.requests.memory }}
              memory: "{{ . }}"
            {{- end }}
            {{- with .Values.requests.cpu }}
              cpu: "{{ . }}"
            {{- end }}
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP

          env:
            - name: APP_DB_HOST
              value: 127.0.0.1

            - name: SMTP_RELAY_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "short_name" . }}
                  key: SMTP_RELAY_HOST

            - name: SMTP_RELAY_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "short_name" . }}
                  key: SMTP_RELAY_PORT

            - name: SMTP_RELAY_MYHOSTNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "short_name" . }}
                  key: SMTP_RELAY_MYHOSTNAME

            - name: SMTP_RELAY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "short_name" . }}
                  key: SMTP_RELAY_USERNAME

            - name: SMTP_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "short_name" . }}
                  key: SMTP_RELAY_PASSWORD

            - name: SMTP_RELAY_NETWORKS
              valueFrom:
                secretKeyRef:
                  name: {{ include "short_name" . }}
                  key: SMTP_RELAY_NETWORKS


            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          volumeMounts:
          - mountPath: /var/spool/postfix
            name: data

      volumes:
      - name: data
        emptyDir: {}


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
