apiVersion: v1
kind: Secret
metadata:
  name: {{ include "short_name" . }}
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
data:
  SMTP_RELAY_HOST: {{ .Values.smtp.relay.host | b64enc }}
  SMTP_RELAY_PORT: {{ .Values.smtp.relay.port | b64enc }}
  SMTP_RELAY_MYHOSTNAME: {{ .Values.smtp.relay.myhostname | b64enc }}
  SMTP_RELAY_USERNAME: {{ .Values.smtp.relay.username | b64enc }}
  SMTP_RELAY_PASSWORD: {{ .Values.smtp.relay.password | b64enc }}
  SMTP_RELAY_NETWORKS: {{ .Values.smtp.relay.networks | b64enc }}
