apiVersion: v1
kind: Service
metadata:
  name: {{ include "short_name" . }}
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "short_name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

  type: ClusterIP
  ports:
    - port: 25
      targetPort: 25
      name: smtp
      protocol: TCP
