---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "short_name" $ }}-env-vars
  labels:
    {{- include "chart_labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- if $.Values.global.commonAnnotations }}
    {{- $.Values.global.commonAnnotations | toYaml | nindent 4 }}
  {{- end }}
data:
  {{- with $.Values.extraEnvVars }}
  {{- range $k, $v := . }}
  "{{ $k }}": {{ tpl $v $ | quote }}
  {{- end }}
  {{- end }}