{{- if $.Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "short_name" $ }}
  labels:
    {{- include "chart_labels" $ | nindent 4 }}
  {{- with $.Values.persistence.labels }}
    {{- . | toYaml | nindent 4 }}
  {{- end }}

  {{- if or $.Values.persistence.annotations $.Values.global.commonAnnotations }}
  annotations:
    {{- if  $.Values.persistence.annotations }}
    {{- $.Values.persistence.annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- if $.Values.global.commonAnnotations }}
    {{- $.Values.global.commonAnnotations | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}

spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ $.Values.persistence.size | quote }}

{{- if $.Values.persistence.storageClass }}
{{- if (eq "-" $.Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ $.Values.persistence.storageClass }}"
{{- end }}
{{- end }}

{{- end }}
