apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "itsm-ng.fullname" . }}
  labels:
    {{- include "itsm-ng.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "itsm-ng.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "itsm-ng.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "itsm-ng.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 5
            httpGet:
              path: /
              port: http
          readinessProbe:
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            httpGet:
              path: /
              port: http
          env:
          - name: TIMEZONE
            value: {{ .Values.itsmTimezone }}
          - name: DBDATABASE
            value: {{ .Values.itsmDbDatabase }}
          - name: DBUSER
            value: {{ .Values.itsmDbUser }}
          - name: DBPASSWORD
            value: {{ .Values.itsmDbPassword }}
          - name: DBHOST
            value: {{ include "mariadb.primary.fullname" .Subcharts.mariadb }}
          - name: ITSM_ADMIN_PASSWORD
            value: {{ .Values.itsmAdminPassword }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
