apiVersion: v1
kind: Service
metadata:
  name: apache-varnish-php-mysql-sftp-{{ include "short_name" . }}
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "short_name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
      protocol: TCP

    - port: 80
      targetPort: {{ ternary 8080 80 .Values.varnish.enabled }}
      name: http
      protocol: TCP

    - port: 22
      targetPort: 22
      name: sftp
      protocol: TCP

{{- if and (gt (len (default "" (toString .Values.sftp.port))) 0) (or (gt (len (default "" .Values.sftp.users.with_password)) 0) (gt (len (default "" .Values.sftp.users.with_key)) 0)) }}
---
apiVersion: v1
kind: Service
metadata:
  name: apache-varnish-php-mysql-sftp-{{ include "short_name" . }}-sftp
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "short_name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

  type: NodePort
  ports:
    - port: {{ .Values.sftp.port }}
      nodePort: {{ .Values.sftp.port }}
      targetPort: 22
      name: sftp
      protocol: TCP
      {{- with .Values.sftp.externalIP }}
  externalTrafficPolicy: Local
  externalIPs:
    - {{ . }}
  {{- end }}

  {{- end }}
