apiVersion: v1
kind: Secret
metadata:
  name: apache-varnish-php-mysql-sftp-{{ include "short_name" . }}
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
data:
  db_name: {{ .Values.secrets.db_name | b64enc }}
  db_user: {{ .Values.secrets.db_user | b64enc }}
  db_password: {{ .Values.secrets.db_password | b64enc }}
  db_root_password: {{ .Values.secrets.db_root_password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: apache-varnish-php-mysql-sftp-{{ include "short_name" . }}-sftp
  labels:
{{ include "chart_labels" . | indent 4 }}
type: Opaque
stringData:
  users.conf: |-
{{- with .Values.sftp.users.with_password }}
{{- range splitList "\n" . }}
    {{ (split ":" .)._0 }}:{{ (split ":" .)._1 }}:{{ $.Values.sftp.uid }}:{{ $.Values.sftp.gid }}:html
{{- end }}
{{- end }}
{{- with .Values.sftp.users.with_key }}
{{- range splitList "\n" . }}
    {{ (split ":" .)._0 }}::{{ $.Values.sftp.uid }}:{{ $.Values.sftp.gid }}:html
{{- end }}
{{- end }}

{{- with .Values.sftp.users.with_key }}
{{- range splitList "\n" . }}
  {{ (split ":" .)._0 }}_ssh: {{ (split ":" .)._1 }}
{{- end }}
{{- end }}
