# Default values for jmeter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "docker.io/admantic/jmeter-for-monitoring/jmeter-monitoring"
  pullPolicy: IfNotPresent

  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}
podLabels: {}

podSecurityContext: {}


securityContext: {}


resources: {}


livenessProbe: {}
readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}

jmxURL: ""
args: []
#  - -JapiFqdn: api.test.com
#  - -JapiPath: /api/v1/testRoute