{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingress4netpol-knocking.serviceAccountName" . }}
  labels:
    {{- include "ingress4netpol-knocking.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ingress4netpol-knocking.fullname" . }}
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ingress4netpol-knocking.fullname" . }}
subjects:
- kind: ServiceAccount
  name:  {{ include "ingress4netpol-knocking.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ingress4netpol-knocking.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
