---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "short_name" . }}-wg-conf-pvc
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
