---
{{- if $.Values.ingress.basicAuth.enabled }}
kind: Secret
metadata:
  name: basic-auth-{{ include "short_name" $ }}
apiVersion: v1
data:
  {{- range $user, $password := $.Values.ingress.basicAuth.auth }}
  {{ $user }}: {{ $password }}
  {{- end }}
type: Opaque
{{- end }}