---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "short_name" $ }}
  labels:
    {{- include "chart_labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "chart_labels" $ | nindent 4 }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
