apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matterbridge.fullname" . }}
  labels:
    {{- include "matterbridge.labels" . | nindent 4 }}
type: Opaque
data:
  matterbridge.toml: "{{ .Values.matterbridge.config | b64enc }}"