image:
  repository: admantic/k8s-ingress4netpol-knocking
  pullPolicy: IfNotPresent
  tag: v0.1.6

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
  hosts: []
    # - host: chart-example.local
    #   paths:
    #     - path: /CHANGEME-BY-A-RANDOM-STRING
    #       pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

networkPolicies:
  namePrefix: ingress4netpol-knocking
  targetLabels: {}
    # app.kubernetes.io/name: myApp
    # app.kubernetes.io/managed-by: Helm
    # release: myRelease
  allowPorts: []
  # - 30000/TCP
  allowDuration: 60 # minutes
  proxyHeader: ~
  trustedProxies: [] # single IPs, PHP lib doesn't support CIDR

service:
  type: ClusterIP
  port: 80

serviceAccount:
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 0
  readOnlyRootFilesystem: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

tolerations: []
