---
image:
  imagePullSecrets: []
  registry: docker.io
  repository: admantic/keepalived-for-kubernetes
  tag: "v0.4"
  imagePullPolicy: IfNotPresent

auth:
  password: ""

configuration:
  - node_ips: []
    vips: []
    gw: ""

extraEnvVars: {}

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists