---
image:
  imagePullSecrets: []
  registry: docker.io
  repository: admantic/keepalived-for-kubernetes
  tag: "v0.3"
  imagePullPolicy: IfNotPresent

auth:
  password: ""

configuration:
  - node_ips: []
    vips: []
    gw: ""

extraEnvVars: {}

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi