{{- with .Values.extraConfigMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "short_name" $ }}
  labels:
    {{- include "chart_labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{ base .mountPath }}: |
    {{- .content | nindent 4 }}
{{- end }}