---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "short_name" $ }}
type: Opaque
data:
{{- with .Values.secretData }}
{{- range $key, $value := . }}
  {{ $key }}: {{ tpl $value $ | b64enc }}
{{- end }}
{{- end }}