{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pv-heartbeat.serviceAccountName" . }}
  labels:
    {{- include "pv-heartbeat.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-heartbeat
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-heartbeat-{{ include "pv-heartbeat.fullname" . }}
subjects:
- kind: ServiceAccount
  name:  {{ include "pv-heartbeat.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: pv-heartbeat
  apiGroup: rbac.authorization.k8s.io
{{- end }}
