{{- with .Values.applications }}
{{- range . }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  {{- if or .prune (and $.Values.global.prune (not (hasKey . "prune"))) }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}
spec:
  destination:
    {{- tpl ((mergeOverwrite (dict) (deepCopy (default (dict) $.Values.global.destination)) (deepCopy (default (dict) .destination))) | toYaml) . | nindent 4 }}
  project: {{ coalesce $.Values.global.project .project | quote }}
  sources: 
    {{- tpl (coalesce $.Values.global.sources .sources | toYaml) . | nindent 4 }}
  syncPolicy:
    {{- tpl ((mergeOverwrite (dict) (deepCopy (default (dict) $.Values.global.syncPolicy)) (deepCopy (default (dict) .syncPolicy))) | toYaml) . | nindent 4 }}

{{- end }}
{{- end }}
