{{- if .Values.webui.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crowdsec-all-in-one.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crowdsec-all-in-one.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- toYaml .Values.webui.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.webui.persistence.size }}
  {{- if .Values.webui.persistence.storageClass }}
  storageClassName: {{ .Values.webui.persistence.storageClass }}
  {{- end }}
{{- end }}
