name: zulip
description: A chart Helm for Zulip, open source group chat application
version: 0.4.8-1
apiVersion: v2
icon: https://github.com/zulip/zulip/raw/master/static/images/logo/zulip-icon-512x512.png
dependencies:
  - name: redis
    version: "12.8.3"
    repository: "https://charts.bitnami.com/bitnami"

  - name: memcached
    version: "5.6.0"
    repository: "https://charts.bitnami.com/bitnami"

  - name: rabbitmq
    version: "8.11.3"
    repository: "https://charts.bitnami.com/bitnami"
