---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-default-backend.fullname" . }}-config
  labels:
    {{- include "nginx-default-backend.labels" . | nindent 4 }}
data:
  {{- with $.Values.config }}
  {{- range $k, $v := . }}
  "{{ $k }}": {{ tpl $v $ | quote }}
  {{- end }}
  {{- end }}