---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-default-backend.fullname" . }}-config
  labels:
    {{- include "nginx-default-backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{- with $.Values.config }}
  {{- range $k, $v := . }}
  "{{ $k }}": {{ tpl $v $ | quote }}
  {{- end }}
  {{- end }}