---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-default-backend.fullname" . }}-content
  labels:
    {{- include "nginx-default-backend.labels" . | nindent 4 }}
data:
  {{- with $.Values.content }}
  {{- range $k, $v := . }}
  {{ $k | quote }}: {{ tpl $v $ | quote }}
  {{- end }}
  {{- end }}

binaryData:
  {{- with $.Values.contentEncoded }}
  {{- range $k, $v := . }}
  {{ $k | quote }}: {{ tpl $v $ | quote }}
  {{- end }}
  {{- end }}
