apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-token"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    helm.sh/hook-weight: "20"
    kubernetes.io/service-account.name: "{{ $.Release.Name }}"
type: kubernetes.io/service-account-token