image:
  repository: "docker.io/admantic/jmeter-for-monitoring/jmeter-monitoring"
  pullPolicy: IfNotPresent
  tag: 0.1.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

jmxURL: ""
args: []
#  - -JapiFqdn: api.test.com
#  - -JapiPath: /api/v1/testRoute