image:
  repository: "docker.io/admantic/jmeter-for-monitoring/jmeter-monitoring"
  pullPolicy: IfNotPresent
  tag: 5.6.3-0.1.0


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
extraEnv: {}
# extraConfigMap:
#   - name: <UNIQUE_NAME>
#     mountPath: <PATH>
#     content: <CONTENT>
extraConfigMap: []

jmxURL: ""
args: []
#  - -JapiFqdn: api.test.com
#  - -JapiPath: /api/v1/testRoute

apache:
  enabled: false
  service:
    port: 80
    type: ClusterIP
    clusterIP: ""
  ingress:
    enabled: false
    pathType: ImplementationSpecific
    hostname: ""
    path: /
    annotations: {}
    ingressClassName: nginx
    tls: true
    extraHosts: []