---
global:
  commonAnnotations: {}
  imagePullSecrets: []

auth:
  adminUser: ""
  adminPassword: ""

persistence:
  enabled: false
  storageClass: ""
  size: ""
  labels: {}
  annotations: {}

service:
  type: ClusterIP
  port: 80
  clusterIP: ""
  annotations: {}

annotations: {}
podAnnotations: {}
replicas: 1
securityContext: {}
image:
  imagePullSecrets: []
  registry: docker.io
  repository: tuxgasy/dolibarr
  tag: "16.0.3"
  imagePullPolicy: IfNotPresent
command: ""
containerPort: 80
livenessProbe: {}
startupProbe: {}
readinessProbe: {}
resources: {}
extraEnvVars:
  DOLI_DB_HOST: "{{ .Release.Name }}-mariadb.{{ .Release.Namespace }}.svc.cluster.local"
  DOLI_DB_USER: "{{ .Values.mariadb.auth.username }}"
  DOLI_DB_PASSWORD: "{{ .Values.mariadb.auth.password }}"
  DOLI_DB_NAME: "{{ .Values.mariadb.auth.database }}"
  PHP_INI_DATE_TIMEZONE: "Europe/Paris"
  DOLI_ADMIN_LOGIN: "{{ .Values.auth.adminUser }}"
  DOLI_ADMIN_PASSWORD:  "{{ .Values.auth.adminPassword }}"

ingress:
  enabled: false
  pathType: ImplementationSpecific
  hostname: ""
  path: /
  annotations:
    kubernetes.io/tls-acme: "true"
  ingressClassName: nginx
  tls: true
  extraHosts: []

mariadb:
  enabled: true
  auth:
    database: ""
    rootPassword: ""
    username: ""
    password: ""
  primary:
    persistence:
      size: 5G
      storageClass: ""