apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jmeter.fullname" . }}
  labels:
    {{- include "jmeter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jmeter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jmeter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.apache.enabled }}
          ports:
            - name: app
              containerPort: {{ .Values.apache.service.port }}
              protocol: TCP
          {{- end }}
          env:
            - name: JMX_URL
              value: "{{ .Values.jmxURL}}"
          {{- if .Values.apache.enabled }}
            - name: WITH_APACHE
              value: "true"
          {{- end }}
{{- with .Values.extraEnv }}
{{- range $k, $v := . }}
            - name: "{{ $k }}"
              value: "{{ tpl $v $ }}"
{{- end }}
{{- end }}

          args:
            {{- toYaml .Values.args | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.volumeMounts .Values.extraConfigMap }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- range .Values.extraConfigMap }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ base .mountPath }}
              readOnly: true
          {{- end }}
          {{- end }}
      {{- if or .Values.volumes .Values.extraConfigMap }}
      volumes:
      {{ with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- range .Values.extraConfigMap }}
        - name: {{ .name }}
          configMap:
            name: "{{ include "jmeter.fullname" $ }}-{{ .name }}"
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
