{{- if .Values.apache.enabled }}
---
{{- if .Values.apache.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jmeter.fullname" . }}
  labels:
    {{- include "jmeter.labels" . | nindent 4 }}
  {{- if .Values.apache.ingress.annotations}}
  annotations:
    {{- .Values.apache.ingress.annotations | toYaml | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: {{ .Values.apache.ingress.ingressClassName | quote }}

  tls:
    - hosts:
        - {{ .Values.apache.ingress.hostname }}
      secretName: {{ regexReplaceAll "\\W+" .Values.apache.ingress.hostname "-" }}-tls

    {{- with .Values.apache.ingress.extraHosts }}
    {{- range . }}
    - hosts:
        - {{ . }}
      secretName: {{ regexReplaceAll "\\W+" . "-" }}-tls
    {{- end }}
    {{- end }}

  rules:
    - host: {{ .Values.apache.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jmeter.fullname" . }}
                port:
                  name: app
  {{- with .Values.apache.ingress.extraHosts }}
  {{- range . }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jmeter.fullname" . }}
                port:
                  name: app
  {{- end }}
  {{- end }}

{{- end }}
{{- end }}