---
{{- if .Values.apache.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jmeter.fullname" . }}
  labels:
    {{- include "jmeter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apache.service.type }}
  {{- if .Values.apache.service.clusterIP }}
  clusterIP: {{ .Values.apache.service.clusterIP }}
  {{- end }}
  ports:
    - name: app
      port: {{ .Values.apache.service.port }}
      targetPort: app
  selector:
    {{- include "jmeter.labels" . | nindent 4 }}
{{- end }}