name: Publish Charts

on:
  push:
    branches:
      - master

jobs:

  publish:

    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.18.1
    steps:
    - uses: actions/checkout@v2

    - name: Authenticate to GHCR
      run: |
        echo "${{ secrets.GHCR_TOKEN }}" | helm registry login ghcr.io/admantic/helm-charts --username bmalynovytch --password-stdin

    - name: Package Charts
      run: |
        set -ex
        rm -rf packaged-charts
        mkdir packaged-charts
        for CHART in charts/*/ ;
        do
          helm package -d packaged-charts $CHART ;
        done;

    - name: Push to Chartmuseum
      run: |
        set -ex
        for CHART in packaged-charts/* ; do helm push --force $CHART oci://ghcr.io/admantic/helm-charts ; done